version: '2'
template:
  name: 'template name'
  required:
    - build
    - repo
toolchain:
  name: '{{baseName}}-{{timestamp}}'
services:
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{toolchain.name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          BIND_TO: '{{bindTo}}'
          CF_APP_NAME: '{{form.pipeline.parameters.prod-app-name}}'
          PROD_SPACE_NAME: '{{form.pipeline.parameters.prod-space}}'
          PROD_ORG_NAME: '{{form.pipeline.parameters.prod-organization}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
        execute: true
  repo:
    service_id: githubpublic
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: '{{repository}}'
      type: clone
      has_issues: true
      enable_traceability: true
form:
  pipeline:
    parameters:
      prod-app-name: '{{services.repo.parameters.repo_name}}'
